name: Deploy app to Droplet

on:
  push:
    branches:
      - main

env:
  DROPLET_IP: 137.184.6.236
  DOCKER_IMAGE: ghcr.io/teodoro-systems/l34ds-api:latest
  NODEJS_RUNTIME_PORT: 3005

jobs:
  build_and_push_to_registry:
    name: Build and push Docker image to GitHub Container Registry (GHCR.io)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build . --tag ${{ env.DOCKER_IMAGE }}
          docker push ${{ env.DOCKER_IMAGE }}

  pull_and_run_container:
    name: Pull Docker image and run within Docker Droplet
    needs: build_and_push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Access Droplet and start container
        run: |
          ssh root@${{ env.DROPLET_IP }} '
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin 
            docker pull ${{ env.DOCKER_IMAGE }}
            docker run -d -p ${{ env.NODEJS_RUNTIME_PORT }}:${{ env.NODEJS_RUNTIME_PORT }} ${{ env.DOCKER_IMAGE }}
            echo "Successfully spun up docker container!"
          '
